version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: vue-property-decorator
    versions:
    - 8.5.1
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
